//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Property
{
    public int PropertyID { get; set; }
    public string UserName { get; set; }
    public string PropertyName { get; set; }
    public string ImgPath { get; set; }
    public double Price { get; set; }
    public string PType { get; set; }
    public double Size { get; set; }
    public string PAddress { get; set; }
    public System.DateTime ListDate { get; set; }
    public string PDescription { get; set; }
}
